# Generated by Django 3.0.3 on 2020-04-04 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifydata',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='spotifydata',
            name='token',
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=256)),
                ('token_type', models.CharField(max_length=256)),
                ('refresh_token', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='spotify.SpotifyData')),
            ],
        ),
    ]
