# Generated by Django 3.0.3 on 2020-04-04 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_auto_20200404_0947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
