# Generated by Django 3.0.3 on 2020-04-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_delete_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifydata',
            name='access_token',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='spotifydata',
            name='refresh_token',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='spotifydata',
            name='token_type',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
