# Generated by Django 3.0.3 on 2020-04-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0006_auto_20200404_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifydata',
            name='expires_at',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spotifydata',
            name='expires_in',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
