# Generated by Django 4.2.4 on 2023-08-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_auto_20200405_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifydata',
            name='expires_in',
        ),
        migrations.RemoveField(
            model_name='spotifydata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='spotifydata',
            name='token_type',
        ),
        migrations.AddField(
            model_name='spotifydata',
            name='category',
            field=models.CharField(default='Test', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spotifydata',
            name='access_token',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='spotifydata',
            name='refresh_token',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='spotifydata',
            name='sp_name',
            field=models.CharField(max_length=512, primary_key=True, serialize=False),
        ),
    ]
